apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      protocol: TCP
status:
  loadBalancer: {}
