apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dev-tech-challenge-network: "true"
        app: api
    spec:
      containers:
      - name: api
        image: carevon/apiweb
        ports:
        - containerPort: 3000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: mysql-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: mysql-password                
        - name: DB_USER
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: mysql-user
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
                name: mysql-configmap
                key: database_url
