apiVersion: v1
kind: Secret
metadata:
 name: mysql-secret
type: Opaque
data:
    mysql-db: RGVsaXZlcnlTeXN0ZW0=
    mysql-user: TWFpblVzZXI=
    mysql-password: TWFpblBhc3N3b3Jk
    mysql-root-password: Um9vdFBhc3N3b3Jk